name: Visual Regression Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install --with-deps
      
    - name: Build Storybook
      run: npm run build-storybook
      
    - name: Start Storybook
      run: npx http-server storybook-static -p 6006 &
      
    - name: Run Percy Tests
      run: npx percy exec -- npx playwright test src/tests/visual/stories/
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-results
        path: test-results/